//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footy_AI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Event
    {
        public int E_id { get; set; }
        public string Event_type { get; set; }
        public string Event_name { get; set; }
        public string VideoPath { get; set; }
        public string Description { get; set; }
    }
}
