//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footy_AI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Match
    {
        public int M_id { get; set; }
        public System.DateTime M_date { get; set; }
        public string M_location { get; set; }
        public Nullable<int> User_id { get; set; }
    }
}
