//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footy_AI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Occur_By
    {
        public int Occur_id { get; set; }
        public Nullable<int> E_id { get; set; }
        public Nullable<int> Pl_id { get; set; }
        public Nullable<int> P_id { get; set; }
        public Nullable<System.TimeSpan> start_time { get; set; }
        public Nullable<System.TimeSpan> end_time { get; set; }
    }
}
