//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Footy_AI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Player
    {
        public int P_id { get; set; }
        public string P_name { get; set; }
        public Nullable<int> jersey_no { get; set; }
        public Nullable<int> T_id { get; set; }
    }
}
